# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "llvm-msvc-seh-test"
msvc-runtime = "static"

[fetch-content.googletest]
git = "https://github.com/google/googletest"
tag = "v1.13.0"

[target.test_seh]
type = "executable"
sources = ["src/**.cpp"]
include-directories = ["googletest/googletest/include"]
link-libraries = ["gtest"]
compile-features = ["cxx_std_20"]
compile-options = ["/EHa"]
