name: build-win32

permissions:
  contents: write
  
on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: windows-2022
    steps:
    
    - name: Setup llvm-msvc
      uses: NewWorldComingSoon/setup-llvm-msvc@v2
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        cmake -Bbuild32 -TLLVM-MSVC_v143 -AWin32
        cmake --build build32 --config Release
    
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ github.sha }}
        path: |
          build32/Release
    
    - name: Compress artifacts
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
         build32/Release/*.*
        dest: ${{ github.event.repository.name }}-${{ github.sha }}-32.zip

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: ${{ github.event.repository.name }}-${{ github.sha }}-32.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
